# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='fans',
            field=models.ManyToManyField(related_name='liked_wishes', to='wishing_app.User'),
        ),
    ]
