# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishing_app', '0003_auto_20190920_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
